apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-learn-data
  namespace: default
  labels:
    app: postgres-learn
    env: production
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
